var gvjs_No=" 0 0 1 ",gvjs_Oo="0%",gvjs_Po="100%",gvjs_Qo="BUTTON",gvjs_Ro="SELECT",gvjs_So="TEXTAREA",gvjs_To="background",gvjs_Uo="baseline",gvjs_Vo="blur",gvjs_Wo="chartArea.bottom",gvjs_Xo="chartArea.height",gvjs_Yo="chartArea.left",gvjs_Zo="chartArea.right",gvjs__o="chartArea.top",gvjs_0o="chartArea.width",gvjs_1o="circle",gvjs_2o="clip-path",gvjs_3o="corners.bottomleft.rx",gvjs_4o="corners.bottomleft.ry",gvjs_5o="corners.bottomright.rx",gvjs_6o="corners.bottomright.ry",gvjs_7o="corners.rx",
gvjs_8o="corners.ry",gvjs_9o="corners.topleft.rx",gvjs_$o="corners.topleft.ry",gvjs_ap="corners.topright.rx",gvjs_bp="corners.topright.ry",gvjs_cp="datatable",gvjs_dp="datum",gvjs_ep="defs",gvjs_fp="discrete",gvjs_gp="ellipse",gvjs_R="end",gvjs_hp="feComponentTransfer",gvjs_ip="feGaussianBlur",gvjs_jp="feMergeNode",gvjs_kp="fill",gvjs_lp="fill-opacity",gvjs_mp="fill.color",gvjs_np="fill.opacity",gvjs_op="fillColor",gvjs_pp="fillOpacity",gvjs_qp="filter",gvjs_rp="finishAnimation",gvjs_sp="font.family",
gvjs_tp="font.size",gvjs_up="fontFamily",gvjs_vp="fontName",gvjs_wp="fontSize",gvjs_xp="getcontext",gvjs_yp="gradient",gvjs_zp="group",gvjs_Ap="halign",gvjs_S="horizontal",gvjs_Bp="http://www.w3.org/2000/svg",gvjs_Cp="in",gvjs_Dp="italic",gvjs_Ep="linear",gvjs_Fp="linearGradient",gvjs_Gp="offset",gvjs_Hp="opacity",gvjs_Ip="path",gvjs_Jp="playAnimation",gvjs_Kp="point",gvjs_Lp="pointShape",gvjs_T="px",gvjs_Mp="rabl-use-parent",gvjs_Np="rect",gvjs_Op="redraw",gvjs_Pp="rotate",gvjs_Qp="rotate(",gvjs_Rp=
"rtl",gvjs_Sp="shadow.opacity",gvjs_Tp="shadow.radius",gvjs_Up="shadow.xoffset",gvjs_Vp="shadow.yoffset",gvjs_Wp="slice",gvjs_Xp="stop",gvjs_Yp="stroke",gvjs_Zp="stroke-opacity",gvjs__p="stroke-width",gvjs_0p="stroke.color",gvjs_1p="stroke.opacity",gvjs_2p="stroke.width",gvjs_3p="strokeColor",gvjs_4p="strokeOpacity",gvjs_5p="strokeWidth",gvjs_6p="svg",gvjs_7p="text-anchor",gvjs_8p="transform",gvjs_9p="underline",gvjs_$p='unknown property on ellipse "',gvjs_aq="url(#",gvjs_bq="valign",gvjs_U="vertical";
function gvjs_V(a,b){return gvjs_2d[a]=b}gvjs_B.prototype.La=gvjs_V(10,function(){return this.right-this.left});gvjs_Nn.prototype.La=gvjs_V(9,function(a,b){return a.bD(gvjs_Xd)||gvjs_Gh(this.container).width||b||400});function gvjs_cq(a,b,c){gvjs_Ne(a,c,0,b)}function gvjs_dq(a,b,c){b=gvjs_iaa(b,function(d,e){var f={};return f[e]=d,f},c);gvjs_kj(a,b)}
function gvjs_eq(a,b,c){if(a.oN){var d={};gvjs_dq(d,a.oN[0].split("."),c);c=d}for(var e=d=0;e<b;e++)e===a.AJ.length&&a.AJ.push(0),d+=a.AJ[e];a.AJ[b]++;gvjs_cq(a.Gd,c,d)}function gvjs_fq(a,b){for(var c=gvjs_8d(Object.keys(b)),d=c.next();!d.done;d=c.next()){d=d.value;var e=b[d];null!=e&&e instanceof Object&&!Array.isArray(e)?(a[d]=a[d]||{},gvjs_fq(a[d],e)):null!=e&&(a[d]=e)}}function gvjs_gq(a){var b=void 0===b?{}:b;gvjs_Ce(a.Gd,function(c){gvjs_fq(b,c)});return b}
function gvjs_hq(a,b,c){return gvjs_Dj(a,gvjs_Jj,0,b,c)}function gvjs_iq(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return gvjs_iq.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c}
var gvjs_bda=/<[^>]*>|&[^;]+;/g,gvjs_cda=/[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0900-\u1fff\u200e\u2c00-\ud801\ud804-\ud839\ud83c-\udbff\uf900-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,gvjs_dda=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0900-\u1fff\u200e\u2c00-\ud801\ud804-\ud839\ud83c-\udbff\uf900-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u08ff\u200f\ud802-\ud803\ud83a-\ud83b\ufb1d-\ufdff\ufe70-\ufefc]/,gvjs_eda=/^http:\/\/.*/,gvjs_fda=/\s+/,gvjs_gda=
/[\d\u06f0-\u06f9]/;function gvjs_jq(a,b){var c=0,d=0,e=!1;a=(b?a.replace(gvjs_bda,""):a).split(gvjs_fda);for(b=0;b<a.length;b++){var f=a[b];gvjs_dda.test(f)?(c++,d++):gvjs_eda.test(f)?e=!0:gvjs_cda.test(f)?d++:gvjs_gda.test(f)&&(e=!0)}return 0==d?e?1:0:.4<c/d?-1:1};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var gvjs_hda=function(){if(gvjs_vg){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(gvjs_Rf))?a[1]:"0"}return gvjs_ug?(a=/1[0|1][_.][0-9_.]+/,(a=a.exec(gvjs_Rf))?a[0].replace(/_/g,"."):"10"):gvjs_Eaa?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(gvjs_Rf))?a[1]:""):gvjs_Faa||gvjs_Gaa||gvjs_Haa?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(gvjs_Rf))?a[1].replace(/_/g,"."):""):""}();function gvjs_kq(a){return(a=a.exec(gvjs_Rf))?a[1]:""}
var gvjs_lq=function(){if(gvjs_Laa)return gvjs_kq(/Firefox\/([0-9.]+)/);if(gvjs_y||gvjs_rg||gvjs_qg)return gvjs_Dg;if(gvjs_Kg)return gvjs_mg()?gvjs_kq(/CriOS\/([0-9.]+)/):gvjs_kq(/Chrome\/([0-9.]+)/);if(gvjs_Lg&&!gvjs_mg())return gvjs_kq(/Version\/([0-9.]+)/);if(gvjs_Ig||gvjs_Jg){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(gvjs_Rf);if(a)return a[1]+"."+a[2]}else if(gvjs_Maa)return(a=gvjs_kq(/Android\s+([0-9.]+)/))?a:gvjs_kq(/Version\/([0-9.]+)/);return""}();var gvjs_mq={};function gvjs_nq(){throw Error("Do not instantiate directly");}gvjs_nq.prototype.WN=null;gvjs_nq.prototype.getContent=function(){return this.content};gvjs_nq.prototype.toString=function(){return this.content};function gvjs_oq(){gvjs_nq.call(this)}gvjs_t(gvjs_oq,gvjs_nq);gvjs_oq.prototype.eq=gvjs_mq;gvjs_y&&gvjs_Eg(8);var gvjs_W=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.WN=d);return c}}(gvjs_oq),gvjs_pq=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=String(c);if(!c)return"";c=new b(c);void 0!==d&&(c.WN=d);return c}}(gvjs_oq);var gvjs_qq={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+gvjs_eg(" ",Number(c)-a.length):gvjs_eg(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;0<=b.indexOf("-",
0)?d=f+d+gvjs_eg(" ",a):(b=0<=b.indexOf("0",0)?"0":" ",d=f+gvjs_eg(b,a)+d);return d},d:function(a,b,c,d,e,f,g,h){return gvjs_qq.f(parseInt(a,10),b,c,d,0,f,g,h)}};gvjs_qq.i=gvjs_qq.d;gvjs_qq.u=gvjs_qq.d;gvjs_iq(["A","AREA",gvjs_Qo,"HEAD",gvjs_Na,"LINK","MENU","META","OPTGROUP","OPTION","PROGRESS",gvjs_7a,gvjs_Ro,gvjs_5a,gvjs_So,"TITLE","TRACK"]);function gvjs_rq(){}gvjs_rq.prototype.o=function(a,b){gvjs_sq(this,a);this.cI[a].push(b);return this};gvjs_rq.prototype.Ab=function(a,b){gvjs_sq(this,a);a=this.cI[a];for(var c=null,d=0,e=a.length;d<e;d++)if(a[d]===b){c=d;break}return null!=c?(a.splice(c,1),!0):!1};gvjs_rq.prototype.fireEvent=function(a,b){gvjs_sq(this,a);a=this.cI[a];for(var c=[],d=0,e=a.length;d<e;d++)c.push(a[d]);for(d=0;d<e;d++)c[d].apply(this,b);return 0<e};
function gvjs_sq(a,b){if(!a.cI.hasOwnProperty(b))throw'event type "'+b+'" unknown.';};function gvjs_tq(a){this.cI={add:[],click:[],getcontext:[],mousemove:[],mouseenter:[],mouseleave:[],box:[],redraw:[],remove:[],playAnimation:[],finishAnimation:[]};this.Sb=this.ra=null;this.md={};this.Zn=[];this.oS=[];if(null!=a)for(var b in a)this.setStyle(b,a[b]);this.j6=null}gvjs_t(gvjs_tq,gvjs_rq);gvjs_=gvjs_tq.prototype;gvjs_.data=function(a){return void 0!==a?(this.ra=a,this):this.ra};gvjs_.setData=function(a){this.ra=a;return this};
gvjs_.setStyle=function(a,b){b instanceof Object&&null!=b&&(b=b.toString());if(this.md[a]===b)return!1;this.md[a]=b;this.eo=null;return!0};gvjs_.getStyle=function(a){return this.md[a]};function gvjs_uq(a){null==a.j6&&(a.j6=new gvjs_yj([a.md],void 0,!0));return a.j6}gvjs_.style=function(a,b){return void 0!==b?(this.setStyle(a,b)&&this.fireEvent(gvjs_Op,[this,a]),this):this.getStyle(a)};gvjs_.styles=function(a){for(var b in a)a.hasOwnProperty(b)&&this.style(b,a[b]);return this};
gvjs_.getContext=function(){this.Sb||this.fireEvent(gvjs_xp,[this]);return this.Sb};gvjs_.Qj=gvjs_n(25);gvjs_.Ou=gvjs_n(27);gvjs_.kEa=function(){for(var a=this;0<this.Zn.length;){var b=this.Zn.shift();a.oS.push(b);b.o(gvjs_rp,function(c,d){c=a.oS.indexOf(d);if(0>c)throw"Animation not found.";a.oS.splice(c,1);0===a.oS.length&&a.fireEvent(gvjs_rp,[a])});if(!this.fireEvent(gvjs_Jp,[this,b]))throw"Cannot play animations for shape not in a scene.";}return this};var gvjs_ida=gvjs_p.requestAnimationFrame||gvjs_p.mozRequestAnimationFrame||gvjs_p.webkitRequestAnimationFrame||gvjs_p.msRequestAnimationFrame||function(a){return gvjs_p.setTimeout(function(){return a.call(this,Date.now())},1E3/60)};function gvjs_vq(a){for(var b=0,c=arguments.length;b<c;b++)if(null!=arguments[b])return arguments[b]}
function gvjs_wq(a,b,c,d){gvjs_xq(a,b,c,d);gvjs_yq(a,b,c,d);gvjs_zq(a,b,c,d);gvjs_Aq(a,b,c,d);gvjs_Bq(a,b,c,d);gvjs_Cq(a,b,c,d);gvjs_Dq(a,b,c,d);var e=gvjs_uq(c),f=gvjs_L(e,"clip.width"),g=gvjs_L(e,"clip.height");if(f&&g){var h=gvjs_L(e,"clip.x",0);e=gvjs_L(e,"clip.y",0);var k=["clip",h,e,f,g].join(),l=c.yr;if(c=a.l3(k,l))n=c.getAttribute(gvjs_5c);else{var m=gvjs_Ph();c=m.createElementNS(gvjs_Bp,"clipPath");var n=a.CZ();c.setAttribute(gvjs_5c,n);m=m.createElementNS(gvjs_Bp,gvjs_Np);m.setAttribute("x",
h);m.setAttribute("y",e);m.setAttribute(gvjs_Xd,f);m.setAttribute(gvjs_4c,g);c.appendChild(m);a.R4(k,c,l);for(a=d;a.nodeName!==gvjs_6p;)a=a.parentNode;a=a.querySelector(gvjs_ep)||a;a.insertBefore(c,a.firstChild)}b.setAttribute(gvjs_2o,gvjs_aq+n+")")}else b.hasAttribute(gvjs_2o)&&b.removeAttribute(gvjs_2o)}
function gvjs_yq(a,b,c,d){gvjs_Eq(a,b,c,d,!1);a=gvjs_vq(c.style(gvjs_mp),c.style(gvjs_op),c.style(gvjs_kp));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_kp,a):null===a&&b.removeAttribute(gvjs_kp)}function gvjs_zq(a,b,c){a=gvjs_vq(c.style(gvjs_np),c.style(gvjs_pp),c.style(gvjs_lp));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_lp,a):null===a&&b.removeAttribute(gvjs_lp)}
function gvjs_Aq(a,b,c,d){gvjs_Eq(a,b,c,d,!0);a=gvjs_vq(c.style(gvjs_0p),c.style(gvjs_3p),c.style(gvjs_Yp));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_Yp,a):null===a&&b.removeAttribute(gvjs_Yp)}function gvjs_Bq(a,b,c){a=gvjs_vq(c.style(gvjs_1p),c.style(gvjs_4p),c.style(gvjs_Zp));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_Zp,a):null===a&&b.removeAttribute(gvjs_Zp)}
function gvjs_Cq(a,b,c){a=gvjs_vq(c.style(gvjs_2p),c.style(gvjs_5p),c.style(gvjs__p));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs__p,a):null===a&&b.removeAttribute(gvjs__p)}function gvjs_xq(a,b,c){a=c.style(gvjs_Hp);typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_Hp,a):null===a&&b.removeAttribute(gvjs_Hp)}
function gvjs_Eq(a,b,c,d,e){var f=gvjs_uq(c),g=e?gvjs_Yp:gvjs_kp,h=f.kt(g+".gradient.from"),k=f.kt(g+".gradient.to");e=b.getAttribute(g);if(h&&k){var l=gvjs_hq(f,g+".gradient.x1",gvjs_Oo),m=gvjs_hq(f,g+".gradient.y1",gvjs_Oo),n=gvjs_hq(f,g+".gradient.x2",gvjs_Po),p=gvjs_hq(f,g+".gradient.y2",gvjs_Oo);f=[gvjs_yp,h,k,l,m,n,p].join();var q=c.yr;if(c=a.l3(f,q))g=c.getAttribute(gvjs_5c);else{var r=gvjs_Ph();c=r.createElementNS(gvjs_Bp,gvjs_Fp);g=a.CZ();c.setAttribute(gvjs_5c,g);c.setAttribute("x1",l);
c.setAttribute("y1",m);c.setAttribute("x2",n);c.setAttribute("y2",p);l=r.createElementNS(gvjs_Bp,gvjs_Xp);l.setAttribute("stop-color",h);l.setAttribute(gvjs_Gp,gvjs_Oo);h=r.createElementNS(gvjs_Bp,gvjs_Xp);h.setAttribute("stop-color",k);h.setAttribute(gvjs_Gp,gvjs_Po);c.appendChild(l);c.appendChild(h);a.R4(f,c,q);for(a=d;a.nodeName!==gvjs_6p;)a=a.parentNode;a=a.querySelector(gvjs_ep)||a;a.insertBefore(c,a.firstChild)}a=gvjs_aq+g+")";e!==a&&b.setAttribute(gvjs_kp,a)}else e&&e.substr(0,5)===gvjs_aq&&
b.removeAttribute(g)}
function gvjs_Dq(a,b,c,d){var e=gvjs_uq(c),f=gvjs_hq(e,gvjs_Tp,0),g=gvjs_hq(e,gvjs_Sp,0);if(f||g){var h=e.kt("shadow.xOffset")||e.kt("shadow.x-offset")||e.kt(gvjs_Up)||0,k=e.kt("shadow.yOffset")||e.kt("shadow.y-offset")||e.kt(gvjs_Vp)||0;e=[gvjs_Vo,f,g,h,k].join();var l=c.yr,m=a.l3(e,l);if(m)c=m.getAttribute(gvjs_5c);else{var n=gvjs_Ph();m=n.createElementNS(gvjs_Bp,gvjs_qp);m.setAttribute("x","-100%");m.setAttribute("y","-100%");m.setAttribute(gvjs_Xd,"300%");m.setAttribute(gvjs_4c,"300%");c=a.CZ();
m.setAttribute(gvjs_5c,c);var p=n.createElementNS(gvjs_Bp,gvjs_ip);p.setAttribute(gvjs_Cp,"SourceAlpha");p.setAttribute("stdDeviation",f);f=n.createElementNS(gvjs_Bp,"feOffset");f.setAttribute("dx",h);f.setAttribute("dy",k);if(null!=g){var q=n.createElementNS(gvjs_Bp,gvjs_hp);var r=n.createElementNS(gvjs_Bp,"feFuncA");r.setAttribute(gvjs_Sd,gvjs_Ep);r.setAttribute("slope",g)}g=n.createElementNS(gvjs_Bp,"feMerge");h=n.createElementNS(gvjs_Bp,gvjs_jp);n=n.createElementNS(gvjs_Bp,gvjs_jp);n.setAttribute(gvjs_Cp,
"SourceGraphic");m.appendChild(p);m.appendChild(f);null!=r&&(q.appendChild(r),m.appendChild(q));g.appendChild(h);g.appendChild(n);m.appendChild(g);a.R4(e,m,l);for(a=d;a.nodeName!==gvjs_6p;)a=a.parentNode;a=a.querySelector(gvjs_ep)||a;a.insertBefore(m,a.firstChild)}a=b.getAttribute(gvjs_qp);d=gvjs_aq+c+")";a!==d&&b.setAttribute(gvjs_qp,d)}else b.hasAttribute(gvjs_qp)&&b.removeAttribute(gvjs_qp)}
var gvjs_jda={"fill.color":gvjs_yq,fillColor:gvjs_yq,fill:gvjs_yq,"fill.gradient.from":gvjs_yq,"fill.gradient.to":gvjs_yq,"fill.gradient.x1":gvjs_yq,"fill.gradient.y1":gvjs_yq,"fill.gradient.x2":gvjs_yq,"fill.gradient.y2":gvjs_yq,"fill.opacity":gvjs_zq,fillOpacity:gvjs_zq,"fill-opacity":gvjs_zq,height:function(a,b,c){a=gvjs_L(gvjs_uq(c),gvjs_4c);b.setAttribute(gvjs_4c,a)},opacity:gvjs_xq,"shadow.radius":gvjs_Dq,"shadow.opacity":gvjs_Dq,"shadow.xOffset":gvjs_Dq,"shadow.x-offset":gvjs_Dq,"shadow.xoffset":gvjs_Dq,
"shadow.yOffset":gvjs_Dq,"shadow.y-offset":gvjs_Dq,"shadow.yoffset":gvjs_Dq,"stroke.color":gvjs_Aq,strokeColor:gvjs_Aq,stroke:gvjs_Aq,"stroke.gradient.from":gvjs_Aq,"stroke.gradient.to":gvjs_Aq,"stroke.gradient.x1":gvjs_Aq,"stroke.gradient.y1":gvjs_Aq,"stroke.gradient.x2":gvjs_Aq,"stroke.gradient.y2":gvjs_Aq,"stroke.opacity":gvjs_Bq,strokeOpacity:gvjs_Bq,"stroke-opacity":gvjs_Bq,"stroke.width":gvjs_Cq,strokeWidth:gvjs_Cq,"stroke-width":gvjs_Cq,width:function(a,b,c){a=gvjs_L(gvjs_uq(c),gvjs_Xd);b.setAttribute(gvjs_Xd,
a)},x:function(a,b,c){a=gvjs_L(gvjs_uq(c),"x");b.setAttribute("x",a)},y:function(a,b,c){a=gvjs_L(gvjs_uq(c),"y");b.setAttribute("y",a)}};function gvjs_Fq(a,b,c,d,e,f){f=f||{};return(c=f[c]||gvjs_jda[c])?(c(a,b,d,e),!0):!1};var gvjs_Gq={applyX:function(a,b,c){a=gvjs_uq(c).Aa("x");null!=a&&b.setAttribute("cx",a)},applyY:function(a,b,c){a=gvjs_uq(c).Aa("y");null!=a&&b.setAttribute("cy",a)},p7:function(a,b,c){a=gvjs_uq(c).Aa("r");null!=a&&b.setAttribute("r",a)}};gvjs_Gq.DK={r:gvjs_Gq.p7,x:gvjs_Gq.applyX,y:gvjs_Gq.applyY};
gvjs_Gq.draw=function(a,b,c,d){var e=gvjs_Ph();d=d||e.createElementNS(gvjs_Bp,gvjs_1o);gvjs_Gq.applyX(a,d,b);gvjs_Gq.applyY(a,d,b);gvjs_Gq.p7(a,d,b);gvjs_wq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_Gq.Lf=function(a,b,c,d,e){if(!gvjs_Fq(a,e,c,b,d,gvjs_Gq.DK))throw'unknown property on circle "'+c+'".';};var gvjs_Hq={};function gvjs_Iq(a,b,c){a=gvjs_L(gvjs_uq(c),"x");b.setAttribute("cx",a)}function gvjs_Jq(a,b,c){a=gvjs_L(gvjs_uq(c),"y");b.setAttribute("cy",a)}function gvjs_Kq(a,b,c){a=gvjs_L(gvjs_uq(c),"rx");b.setAttribute("rx",a)}function gvjs_Lq(a,b,c){a=gvjs_L(gvjs_uq(c),"ry");b.setAttribute("ry",a)}var gvjs_Mq={x:gvjs_Iq,y:gvjs_Jq,rx:gvjs_Kq,ry:gvjs_Lq};gvjs_Hq.kCa=gvjs_Kq;gvjs_Hq.lCa=gvjs_Lq;gvjs_Hq.applyX=gvjs_Iq;gvjs_Hq.applyY=gvjs_Jq;
gvjs_Hq.draw=function(a,b,c,d){var e=gvjs_Ph();d=d||e.createElementNS(gvjs_Bp,gvjs_gp);gvjs_Iq(a,d,b);gvjs_Jq(a,d,b);gvjs_Kq(a,d,b);gvjs_Lq(a,d,b);gvjs_wq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_Hq.DK=gvjs_Mq;gvjs_Hq.Lf=function(a,b,c,d,e){if(!gvjs_Fq(a,e,c,b,d,gvjs_Mq))throw gvjs_$p+c+'".';};var gvjs_Nq={q7:function(a,b,c){a=gvjs_L(gvjs_uq(c),"x1");b.setAttribute("x1",a)},s7:function(a,b,c){a=gvjs_L(gvjs_uq(c),"y1");b.setAttribute("y1",a)},r7:function(a,b,c){a=gvjs_L(gvjs_uq(c),"x2");b.setAttribute("x2",a)},t7:function(a,b,c){a=gvjs_L(gvjs_uq(c),"y2");b.setAttribute("y2",a)}};gvjs_Nq.DK={x1:gvjs_Nq.q7,x2:gvjs_Nq.r7,y1:gvjs_Nq.s7,y2:gvjs_Nq.t7};
gvjs_Nq.draw=function(a,b,c,d){var e=gvjs_Ph();d=d||e.createElementNS(gvjs_Bp,gvjs_e);gvjs_Nq.q7(a,d,b);gvjs_Nq.r7(a,d,b);gvjs_Nq.s7(a,d,b);gvjs_Nq.t7(a,d,b);gvjs_wq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_Nq.Lf=function(a,b,c,d,e){if(!gvjs_Fq(a,e,c,b,d,gvjs_Nq.DK))throw gvjs_$p+c+'".';};function gvjs_Oq(a){a%=360;return 0>360*a?a+360:a};function gvjs_Pq(a,b,c,d){var e=gvjs_Ph();e=d||e.createElementNS(gvjs_Bp,gvjs_Ip);d||e.setAttribute("d",gvjs_Qq(c));gvjs_wq(a,e,c,b);return e}
function gvjs_Qq(a){a=a.$u;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];if("GVIZARC"===e[0]){var f=e,g=Number(f[1]),h=Number(f[2]);e=Number(f[3]);var k=Number(f[4]),l=gvjs_Oq(Number(f[5])),m=gvjs_Oq(Number(f[6]));f=!!Number(f[7]);270===l&&0===m?e="A "+e+" "+k+gvjs_No+(e+g)+" "+h:180===l&&270===m?e="A "+e+" "+k+gvjs_No+g+" "+(h-k):0===l&&90===m?e="A "+e+" "+k+gvjs_No+g+" "+(h+k):90===l&&180===m?e="A "+e+" "+k+gvjs_No+(g-e)+" "+h:(g+=Math.cos(m/180*Math.PI)*e,h+=Math.sin(m/180*Math.PI)*k,l=f?m-l:
l-m,0>l&&(l+=360),e="A "+e+" "+k+" 0 "+Number(180<l)+" "+Number(f)+" "+g+" "+h)}else e=e.join(" ");b.push(e)}return b.join(" ")};function gvjs_Rq(a){gvjs_tq.call(this,a);this.eo={x1:null,y1:null,x2:null,y2:null,width:0,height:0};this.$u=[]}gvjs_o(gvjs_Rq,gvjs_tq);gvjs_=gvjs_Rq.prototype;gvjs_.Rk=gvjs_n(32);gvjs_.Ou=gvjs_n(26);gvjs_.clear=function(){this.eo={x1:null,y1:null,x2:null,y2:null,width:0,height:0};this.$u=[]};gvjs_.move=function(a,b){this.$u.push(["M",a,b]);return this};gvjs_.line=function(a,b){this.$u.push(["L",a,b]);return this};
gvjs_.arc=function(a,b,c,d,e,f,g){e=gvjs_Oq(e);f=gvjs_Oq(f);this.$u.push(["GVIZARC",a,b,c,d,e,f,Number(g)]);return this};gvjs_.curve=function(a,b,c,d,e,f){this.$u.push(["C",a,b,c,d,e,f]);return this};gvjs_.close=function(){this.$u.push(["Z"]);return this};function gvjs_Sq(a){var b=gvjs_uq(a);a=b.Aa(gvjs_9o)||0;var c=b.Aa(gvjs_$o)||0,d=b.Aa(gvjs_ap)||0,e=b.Aa(gvjs_bp)||0,f=b.Aa(gvjs_3o)||0,g=b.Aa(gvjs_4o)||0,h=b.Aa(gvjs_5o)||0;b=b.Aa(gvjs_6o)||0;return!!(a||c||d||e||f||g||h||b)}
function gvjs_Tq(a){var b=gvjs_uq(a),c=gvjs_L(b,gvjs_7o,0),d=gvjs_L(b,gvjs_8o,0),e=gvjs_L(b,gvjs_9o,c),f=gvjs_L(b,gvjs_$o,d),g=gvjs_L(b,gvjs_ap,c),h=gvjs_L(b,gvjs_bp,d),k=gvjs_L(b,gvjs_3o,c),l=gvjs_L(b,gvjs_4o,d);c=gvjs_L(b,gvjs_5o,c);d=gvjs_L(b,gvjs_6o,d);var m=gvjs_L(b,gvjs_Xd),n=gvjs_L(b,gvjs_4c),p=gvjs_L(b,"x");b=gvjs_L(b,"y");p=0<=m?p:p+m;b=0<=n?b:b+n;m=Math.abs(m);n=Math.abs(n);if(e+g>m){var q=m/(e+g);e*=q;f*=q;g*=q;h*=q}k+c>m&&(q=m/(k+c),k*=q,l*=q,c*=q,d*=q);f+l>n&&(q=n/(f+l),e*=q,f*=q,k*=
q,l*=q);h+d>n&&(q=n/(h+d),g*=q,h*=q,c*=q,d*=q);return(new gvjs_Rq(a.md)).move(p+m-g,b).arc(p+m-g,b+h,g,h,270,0,!0).line(p+m,b+n-d).arc(p+m-c,b+n-d,c,d,0,90,!0).line(p+k,b+n).arc(p+k,b+n-l,k,l,90,180,!0).line(p,b+f).arc(p+e,b+f,e,f,180,270,!0).close()};var gvjs_Uq={draw:function(a,b,c,d){var e=b.style(gvjs_7o),f=b.style(gvjs_8o),g=gvjs_uq(b),h=gvjs_L(g,gvjs_Xd),k=gvjs_L(g,gvjs_4c),l=gvjs_L(g,"x");g=gvjs_L(g,"y");l=0<=h?l:l+h;g=0<=k?g:g+k;h=Math.abs(h);k=Math.abs(k);if(typeof e===gvjs_g&&typeof f===gvjs_g||!gvjs_Sq(b)){var m=gvjs_Ph();d=d||m.createElementNS(gvjs_Bp,gvjs_Np);d.setAttribute("x",l);d.setAttribute("y",g);d.setAttribute(gvjs_Xd,h);d.setAttribute(gvjs_4c,k);null!=e&&typeof e===gvjs_g&&d.setAttribute("rx",e);null!=f&&typeof f===gvjs_g&&
d.setAttribute("ry",f);gvjs_wq(a,d,b,c)}else b=gvjs_Tq(b),d=gvjs_Pq(a,c,b,d);c&&d.parentNode!==c&&c.appendChild(d);return d},Lf:function(a,b,c,d,e){if(!gvjs_Fq(a,e,c,b,d))switch(c){case gvjs_7o:case gvjs_8o:case gvjs_9o:case gvjs_$o:case gvjs_ap:case gvjs_bp:case gvjs_3o:case gvjs_4o:case gvjs_5o:case gvjs_6o:var f=gvjs_Sq(b),g=e.tagName.toLowerCase();if(g===gvjs_Ip&&!f||g===gvjs_Np&&f)return gvjs_Uq.draw(a,b,d);g===gvjs_Ip?(a=gvjs_Tq(b),a=gvjs_Qq(a),e.setAttribute("d",a)):c===gvjs_7o?e.setAttribute("rx",
gvjs_L(gvjs_uq(b),gvjs_7o)):c===gvjs_8o&&e.setAttribute("ry",gvjs_L(gvjs_uq(b),gvjs_8o));break;default:throw'unknown property on rect "'+c+'".';}}};var gvjs_Vq={};function gvjs_Wq(a,b,c){a=c.style(gvjs_sp)||c.style(gvjs_up)||c.style(gvjs_vp);b.style.fontFamily=typeof a===gvjs_l?a:""}function gvjs_Xq(a,b,c){a=c.style(gvjs_tp)||c.style(gvjs_wp);b.style.fontSize=typeof a===gvjs_g?a+gvjs_T:typeof a===gvjs_l?a:""}function gvjs_Yq(a,b,c){a=c.style("font.weight")||c.style("fontWeight");b.style.fontWeight=typeof a===gvjs_l||typeof a===gvjs_g?String(a):""}function gvjs_Zq(a,b,c){!0===c.style(gvjs_Dp)?b.style.fontStyle=gvjs_Dp:b.style.fontStyle=""}
function gvjs__q(a,b,c){!0===c.style(gvjs_9p)?b.style.textDecoration=gvjs_9p:b.style.textDecoration=""}var gvjs_0q={"font.family":gvjs_Wq,fontFamily:gvjs_Wq,fontName:gvjs_Wq,"font.size":gvjs_Xq,fontSize:gvjs_Xq,"font.weight":gvjs_Yq,fontWeight:gvjs_Yq,italic:gvjs_Zq,underline:gvjs__q};
function gvjs_1q(a,b,c,d,e,f,g,h){var k=gvjs_Ph();f=f||gvjs_m;e=!e||f&&e.tagName!==f?k.createElementNS(gvjs_Bp,f):e;e.textContent=c;c=gvjs_uq(d);e.setAttribute("x",null==g?gvjs_hq(c,"x"):g);e.setAttribute("y",null==h?gvjs_hq(c,"y"):h);e.setAttribute(gvjs_Jd,"cursor:default;-webkit-user-select:none;-moz-osx-font-smoothing:grayscale;");e.style.webkitFontSmoothing="antialiased";gvjs_wq(a,e,d,b);gvjs_Zq(a,e,d);gvjs__q(a,e,d);gvjs_Wq(a,e,d);gvjs_Xq(a,e,d);gvjs_Yq(a,e,d);return e}
function gvjs_2q(a,b,c,d){var e=b.style("lineSpacing")||b.style("line-spacing")||0,f=gvjs_uq(b),g=gvjs_J(f,gvjs_m,""),h=-1==gvjs_jq(g,void 0)&&gvjs_y;typeof g===gvjs_l&&(g=g.split("\n"));var k=gvjs_L(f,"y",0),l=!0;1===g.length&&(g=g[0],l=!1);a=gvjs_1q(a,c,l?"":g,b,d,null,gvjs_L(f,"x",0),k);c&&a.parentNode!==c&&c.appendChild(a);c=[];if(l)for(b=gvjs_Ph(),d=0,k=g.length;d<k;d++){var m=b.createElementNS(gvjs_Bp,"tspan");m.textContent=g[d];m.setAttribute(gvjs_Mp,!0);m.setAttribute("x",gvjs_hq(f,"x"));
m.setAttribute("y",gvjs_hq(f,"y"));var n=a.getBBox().height;0<d&&(n+=e);m.setAttribute("dy",n+gvjs_T);a.appendChild(m);c.push(m)}h&&(a.setAttribute("dir",gvjs_Rp),a.setAttribute(gvjs_7p,gvjs_R));return{group:a,lines:l?c:[a]}}
function gvjs_3q(a,b,c,d){c=gvjs_2q(a,b,c,d);a=c.lines;c=c.group;d=Math.max(0,Math.min(1,b.style(gvjs_Ap)||0));if(isNaN(d)||!isFinite(d))d=0;var e=b.style(gvjs_bq);if(typeof e===gvjs_g){if(e=Math.max(0,Math.min(1,e)),isNaN(e)||!isFinite(e))e=0}else e=gvjs_Uo;var f=c.getBBox(),g=b.style("y")-f.y;var h="tspan"===a[a.length-1].tagName.toLowerCase()?a[a.length-1].getBoundingClientRect().top-c.getBoundingClientRect().top:a[a.length-1].getBBox().y-f.y;var k=b.style("y");if(null==k)return c;if(typeof e===
gvjs_g)k=k+g-f.height*e;else if(e===gvjs_Uo)k=k+g-h;else throw"Unrecognized valign value: "+e;c.setAttribute("y",k);e=0;for(f=a.length;e<f;e++)g=a[e],g.setAttribute("dx",-g.getComputedTextLength()*d+gvjs_T),g.setAttribute("y",k);a=b.style(gvjs_Pp);null!=a&&0!=a&&c.setAttribute(gvjs_8p,gvjs_Qp+a+" "+b.style("x")+" "+b.style("y")+")");return c}gvjs_Vq.gCa=gvjs_Wq;gvjs_Vq.hCa=gvjs_Xq;gvjs_Vq.iCa=gvjs_Yq;gvjs_Vq.jCa=gvjs_Zq;gvjs_Vq.mCa=gvjs__q;gvjs_Vq.BCa=gvjs_1q;gvjs_Vq.draw=gvjs_3q;gvjs_Vq.ICa=gvjs_2q;
gvjs_Vq.DK=gvjs_0q;gvjs_Vq.Lf=function(a,b,c,d,e){var f="x"===c||"y"===c;if(f||!gvjs_Fq(a,e,c,b,d,gvjs_0q))if(c===gvjs_m||c===gvjs_Ap||c===gvjs_bq||f){for(;e&&e.firstChild;)e.removeChild(e.firstChild);a=gvjs_3q(a,b,d,e);if(e!==a)throw"error redrawing text";}else throw'error redrawing text element with changed property "'+c+'".';};var gvjs_4q={draw:function(a,b,c,d){var e=gvjs_Ph();d=d||e.createElementNS(gvjs_Bp,"g");gvjs_wq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d},Lf:function(a,b,c,d){a=gvjs_4q.draw(a,b,c,d);d!==a&&b.getContext().fireEvent("add",[b,a,!1])}};var gvjs_kda={Circle:gvjs_Gq,Ellipse:gvjs_Hq,Line:gvjs_Nq,Path:{draw:function(a,b,c,d){a=gvjs_Pq(a,c,b,d);c&&a.parentNode!==c&&c.appendChild(a);return a},Lf:function(a,b,c,d,e){if(!gvjs_Fq(a,e,c,b,d))throw gvjs_$p+c+'".';}},Rect:gvjs_Uq,Text:gvjs_Vq,Group:gvjs_4q};/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT

*/
/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT
*/
function gvjs_5q(a){gvjs_F.call(this);this.e$=a}gvjs_o(gvjs_5q,gvjs_F);gvjs_5q.prototype.Is=gvjs_n(33);gvjs_5q.prototype.dispatchEvent=function(a,b){gvjs_I(this.e$,a,void 0===b?null:b)};gvjs_5q.prototype.M=function(){this.e$=null;gvjs_F.prototype.M.call(this)};function gvjs_6q(a,b,c,d,e){if(null==a||null==b)null==c&&(c=e),c=Math.max(0,d-c),null==a&&null==b?a=b=c/2:null==a?a=Math.max(0,c-b):b=Math.max(0,c-a);c=Math.max(0,Math.round(d-(a+b)));a=Math.round(a);d=Math.min(d,a+c);return{before:a,after:d,size:d-a}}
function gvjs_7q(a,b,c){var d=a/1.618,e=a-b*(1.618-1),f=b/1.618,g=b-a*(1.618-1);a=gvjs_6q(c.left,c.right,c.width,a,Math.round(d>e?d:(d+2*e)/3));b=gvjs_6q(c.top,c.bottom,c.height,b,Math.round(f>g?f:(f+2*g)/3));return{left:a.before,right:a.after,width:a.size,top:b.before,bottom:b.after,height:b.size}};
